# Generated by Django 2.2.4 on 2019-08-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=50, verbose_name='nome')),
                ('sobrenome_responsavel', models.CharField(max_length=50, verbose_name='sobrenome')),
                ('nome_ong', models.CharField(max_length=255, verbose_name='nome_ong')),
                ('str_cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('str_numero', models.CharField(max_length=5, verbose_name='Número Res.')),
                ('telefone', models.CharField(max_length=255, verbose_name='telefone')),
                ('horario_atendimento', models.CharField(max_length=255, verbose_name='horario_atendimento')),
                ('observacao', models.CharField(max_length=255, verbose_name='observação')),
            ],
        ),
    ]
