# Generated by Django 2.2.4 on 2019-08-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_ong'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ong',
            name='email',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='ong',
            name='referencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='referencia'),
        ),
        migrations.AlterField(
            model_name='ong',
            name='observacao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ong',
            name='str_numero',
            field=models.CharField(max_length=5, verbose_name='número Res.'),
        ),
    ]
